-- BingGoPlus Go Backend V2 schema freeze candidate.
-- PostgreSQL 16+. UUID values are generated by the application.
-- This file is a design artifact; it has not been executed in this planning round.

BEGIN;

CREATE SCHEMA IF NOT EXISTS binggoplus_v2;
SET search_path TO binggoplus_v2, public;

CREATE DOMAIN evm_address AS varchar(42)
  CHECK (VALUE = lower(VALUE) AND VALUE ~ '^0x[0-9a-f]{40}$');
CREATE DOMAIN evm_hash AS varchar(66)
  CHECK (VALUE = lower(VALUE) AND VALUE ~ '^0x[0-9a-f]{64}$');
CREATE DOMAIN uint256_numeric AS numeric(78,0)
  CHECK (VALUE >= 0 AND scale(VALUE) = 0);
CREATE DOMAIN bps_value AS integer
  CHECK (VALUE BETWEEN 0 AND 10000);

CREATE TABLE environments (
  id uuid PRIMARY KEY,
  code text NOT NULL UNIQUE,
  project text NOT NULL CHECK (project = 'binggoplus'),
  chain_id bigint NOT NULL CHECK (chain_id > 0 AND chain_id <> 56),
  rpc_alias text NOT NULL,
  write_enabled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  UNIQUE (project, chain_id)
);

CREATE TABLE deployment_sets (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  version text NOT NULL,
  source_commit varchar(40) NOT NULL CHECK (source_commit ~ '^[0-9a-f]{40}$'),
  abi_manifest_hash evm_hash,
  status text NOT NULL CHECK (status IN (
    'DISCOVERED','STATIC_VERIFIED','LIVE_VERIFIED','ACTIVE',
    'SUPERSEDED','DEACTIVATED','REJECTED'
  )),
  activated_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  UNIQUE (environment_id, version),
  CONSTRAINT deployment_sets_id_environment_uk UNIQUE (id, environment_id)
);
CREATE UNIQUE INDEX one_active_deployment_set_per_environment
  ON deployment_sets(environment_id) WHERE status = 'ACTIVE';

CREATE TABLE contract_instances (
  id uuid PRIMARY KEY,
  deployment_set_id uuid NOT NULL REFERENCES deployment_sets(id),
  contract_key text NOT NULL,
  address evm_address NOT NULL,
  deploy_tx_hash evm_hash,
  deploy_block_number bigint NOT NULL CHECK (deploy_block_number >= 0),
  deploy_block_hash evm_hash NOT NULL,
  deploy_log_index integer CHECK (deploy_log_index >= 0),
  runtime_code_hash evm_hash,
  constructor_args jsonb NOT NULL DEFAULT '{}'::jsonb,
  authoritative boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  UNIQUE (deployment_set_id, contract_key),
  UNIQUE (deployment_set_id, address),
  CONSTRAINT contract_instances_id_deployment_address_uk
    UNIQUE (id, deployment_set_id, address)
);

CREATE TABLE deployment_actions (
  id uuid PRIMARY KEY,
  deployment_set_id uuid NOT NULL REFERENCES deployment_sets(id),
  action_type text NOT NULL CHECK (action_type IN ('DEPLOY','BOOTSTRAP','FINALIZE','OPEN_TRADING')),
  sequence_no integer NOT NULL CHECK (sequence_no >= 0),
  tx_hash evm_hash NOT NULL,
  block_number bigint NOT NULL CHECK (block_number >= 0),
  block_hash evm_hash NOT NULL,
  receipt_status smallint NOT NULL CHECK (receipt_status IN (0,1)),
  evidence_path text NOT NULL,
  created_at timestamptz NOT NULL,
  UNIQUE (deployment_set_id, tx_hash)
);

CREATE TABLE contract_evidence_checks (
  id uuid PRIMARY KEY,
  contract_instance_id uuid NOT NULL REFERENCES contract_instances(id),
  check_key text NOT NULL,
  expected_value jsonb,
  observed_value jsonb NOT NULL,
  verdict text NOT NULL CHECK (verdict IN ('PASS','FAIL','UNKNOWN')),
  observed_block_number bigint NOT NULL CHECK (observed_block_number >= 0),
  observed_block_hash evm_hash NOT NULL,
  checked_at timestamptz NOT NULL,
  UNIQUE (contract_instance_id, check_key, observed_block_hash)
);

CREATE TABLE chain_streams (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  deployment_set_id uuid NOT NULL REFERENCES deployment_sets(id),
  stream_key text NOT NULL,
  start_block bigint NOT NULL CHECK (start_block >= 0),
  enabled boolean NOT NULL DEFAULT true,
  confirmation_depth integer NOT NULL CHECK (confirmation_depth > 0),
  reorg_lookback integer NOT NULL CHECK (reorg_lookback >= confirmation_depth),
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  UNIQUE (deployment_set_id, stream_key),
  CONSTRAINT chain_streams_id_environment_deployment_uk
    UNIQUE (id, environment_id, deployment_set_id),
  CONSTRAINT chain_streams_deployment_environment_fk
    FOREIGN KEY (deployment_set_id, environment_id)
    REFERENCES deployment_sets(id, environment_id)
);

CREATE TABLE chain_stream_contracts (
  environment_id uuid NOT NULL,
  deployment_set_id uuid NOT NULL,
  stream_id uuid NOT NULL,
  contract_instance_id uuid NOT NULL,
  contract_address evm_address NOT NULL,
  CONSTRAINT chain_stream_contracts_pk PRIMARY KEY (
    environment_id,
    deployment_set_id,
    stream_id,
    contract_instance_id,
    contract_address
  ),
  CONSTRAINT chain_stream_contracts_stream_fk
    FOREIGN KEY (stream_id, environment_id, deployment_set_id)
    REFERENCES chain_streams(id, environment_id, deployment_set_id),
  CONSTRAINT chain_stream_contracts_instance_address_fk
    FOREIGN KEY (contract_instance_id, deployment_set_id, contract_address)
    REFERENCES contract_instances(id, deployment_set_id, address)
);

CREATE TABLE chain_leases (
  stream_id uuid PRIMARY KEY REFERENCES chain_streams(id),
  owner_id text NOT NULL,
  fencing_token bigint NOT NULL CHECK (fencing_token > 0),
  acquired_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL CHECK (expires_at > acquired_at),
  updated_at timestamptz NOT NULL
);

CREATE TABLE chain_cursors (
  stream_id uuid PRIMARY KEY REFERENCES chain_streams(id),
  next_block bigint NOT NULL CHECK (next_block >= 0),
  last_confirmed_block bigint,
  last_confirmed_hash evm_hash,
  last_finalized_block bigint,
  last_finalized_hash evm_hash,
  state text NOT NULL CHECK (state IN (
    'BOOTSTRAP','SCANNING','HEALTHY','DEGRADED','REORG_RECOVERY','HALTED'
  )),
  fencing_token bigint NOT NULL CHECK (fencing_token > 0),
  updated_at timestamptz NOT NULL,
  CHECK ((last_confirmed_block IS NULL) = (last_confirmed_hash IS NULL)),
  CHECK ((last_finalized_block IS NULL) = (last_finalized_hash IS NULL))
);

CREATE TABLE chain_blocks (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  number bigint NOT NULL CHECK (number >= 0),
  hash evm_hash NOT NULL,
  parent_hash evm_hash NOT NULL,
  block_time timestamptz NOT NULL,
  canonical boolean NOT NULL,
  finalized boolean NOT NULL DEFAULT false,
  observed_at timestamptz NOT NULL,
  UNIQUE (environment_id, hash),
  CONSTRAINT chain_blocks_environment_number_hash_uk
    UNIQUE (environment_id, number, hash)
);
CREATE UNIQUE INDEX one_canonical_hash_per_block
  ON chain_blocks(environment_id, number) WHERE canonical;

CREATE TABLE chain_raw_events (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  deployment_set_id uuid NOT NULL,
  contract_instance_id uuid NOT NULL,
  stream_id uuid NOT NULL,
  block_number bigint NOT NULL CHECK (block_number >= 0),
  block_hash evm_hash NOT NULL,
  tx_hash evm_hash NOT NULL,
  tx_index integer NOT NULL CHECK (tx_index >= 0),
  log_index integer NOT NULL CHECK (log_index >= 0),
  contract_address evm_address NOT NULL,
  topic0 evm_hash NOT NULL,
  topics jsonb NOT NULL,
  data text NOT NULL CHECK (data ~ '^0x[0-9a-f]*$'),
  event_name text,
  decoded jsonb,
  status text NOT NULL CHECK (status IN ('OBSERVED','CONFIRMED','ORPHANED','DECODE_FAILED')),
  canonical boolean NOT NULL,
  observed_at timestamptz NOT NULL,
  confirmed_at timestamptz,
  UNIQUE (environment_id, block_hash, tx_hash, log_index),
  CONSTRAINT chain_raw_events_stream_contract_address_fk FOREIGN KEY (
    environment_id,
    deployment_set_id,
    stream_id,
    contract_instance_id,
    contract_address
  ) REFERENCES chain_stream_contracts (
    environment_id,
    deployment_set_id,
    stream_id,
    contract_instance_id,
    contract_address
  ),
  CONSTRAINT chain_raw_events_block_fk
    FOREIGN KEY (environment_id, block_number, block_hash)
    REFERENCES chain_blocks(environment_id, number, hash)
);
CREATE UNIQUE INDEX one_canonical_log_identity
  ON chain_raw_events(environment_id, tx_hash, log_index) WHERE canonical;
CREATE INDEX raw_events_scan_order
  ON chain_raw_events(stream_id, block_number, tx_index, log_index);

CREATE TABLE projection_receipts (
  id uuid PRIMARY KEY,
  raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  projector_key text NOT NULL,
  projector_version integer NOT NULL CHECK (projector_version > 0),
  status text NOT NULL CHECK (status IN ('APPLIED','REVERTED','FAILED')),
  result_refs jsonb NOT NULL DEFAULT '[]'::jsonb,
  error jsonb,
  applied_at timestamptz NOT NULL,
  UNIQUE (raw_event_id, projector_key, projector_version)
);

CREATE OR REPLACE FUNCTION reject_projection_receipt_identity_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF ROW(NEW.id, NEW.raw_event_id, NEW.projector_key, NEW.projector_version)
    IS DISTINCT FROM
    ROW(OLD.id, OLD.raw_event_id, OLD.projector_key, OLD.projector_version)
  THEN
    RAISE EXCEPTION 'projection receipt identity is immutable'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER projection_receipts_identity_guard
BEFORE UPDATE OF id, raw_event_id, projector_key, projector_version
ON projection_receipts
FOR EACH ROW
EXECUTE FUNCTION reject_projection_receipt_identity_mutation();

CREATE TABLE token_balance_ledger (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  account evm_address NOT NULL,
  counterparty evm_address,
  direction text NOT NULL CHECK (direction IN ('CREDIT','DEBIT')),
  amount_raw uint256_numeric NOT NULL,
  reason text NOT NULL,
  projector_version integer NOT NULL CHECK (projector_version > 0),
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  created_at timestamptz NOT NULL,
  UNIQUE (source_raw_event_id, account, direction, reason, projector_version)
);

CREATE TABLE token_balances_current (
  environment_id uuid NOT NULL REFERENCES environments(id),
  account evm_address NOT NULL,
  balance_raw uint256_numeric NOT NULL,
  as_of_block_number bigint NOT NULL,
  as_of_block_hash evm_hash NOT NULL,
  projector_version integer NOT NULL CHECK (projector_version > 0),
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (environment_id, account)
);

CREATE TABLE cost_basis_events (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  account evm_address NOT NULL,
  state_before text NOT NULL CHECK (state_before IN ('NONE','KNOWN','UNKNOWN')),
  state_after text NOT NULL CHECK (state_after IN ('NONE','KNOWN','UNKNOWN')),
  token_delta_direction text CHECK (token_delta_direction IN ('CREDIT','DEBIT')),
  token_delta_raw uint256_numeric,
  wbnb_delta_direction text CHECK (wbnb_delta_direction IN ('CREDIT','DEBIT')),
  wbnb_delta_raw uint256_numeric,
  reason text NOT NULL,
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  created_at timestamptz NOT NULL,
  UNIQUE (source_raw_event_id, account, reason)
);

CREATE TABLE cost_basis_current (
  environment_id uuid NOT NULL REFERENCES environments(id),
  account evm_address NOT NULL,
  state text NOT NULL CHECK (state IN ('NONE','KNOWN','UNKNOWN')),
  token_amount_raw uint256_numeric NOT NULL DEFAULT 0,
  wbnb_cost_raw uint256_numeric NOT NULL DEFAULT 0,
  as_of_block_number bigint NOT NULL,
  as_of_block_hash evm_hash NOT NULL,
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (environment_id, account)
);

CREATE TABLE trades (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  account evm_address NOT NULL,
  direction text NOT NULL CHECK (direction IN ('BUY','SELL')),
  amount_in_raw uint256_numeric NOT NULL,
  amount_out_raw uint256_numeric NOT NULL,
  tax_total_raw uint256_numeric NOT NULL DEFAULT 0,
  tax_dividend_raw uint256_numeric NOT NULL DEFAULT 0,
  tax_support_raw uint256_numeric NOT NULL DEFAULT 0,
  tax_burn_raw uint256_numeric NOT NULL DEFAULT 0,
  tax_bps bps_value NOT NULL,
  cost_state text CHECK (cost_state IN ('NONE','KNOWN','UNKNOWN')),
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  block_time timestamptz NOT NULL,
  UNIQUE (source_raw_event_id)
);

CREATE TABLE staking_positions (
  environment_id uuid NOT NULL REFERENCES environments(id),
  account evm_address NOT NULL,
  position_id uint256_numeric NOT NULL,
  principal_raw uint256_numeric NOT NULL,
  accrued_reward_raw uint256_numeric NOT NULL,
  unlock_time timestamptz NOT NULL,
  state text NOT NULL CHECK (state IN ('ACTIVE','WITHDRAWN','EARLY_WITHDRAWN')),
  as_of_block_number bigint NOT NULL,
  as_of_block_hash evm_hash NOT NULL,
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (environment_id, account, position_id)
);

CREATE TABLE staking_events (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  account evm_address NOT NULL,
  position_id uint256_numeric,
  event_type text NOT NULL,
  principal_raw uint256_numeric NOT NULL DEFAULT 0,
  reward_raw uint256_numeric NOT NULL DEFAULT 0,
  penalty_raw uint256_numeric NOT NULL DEFAULT 0,
  projector_version integer NOT NULL CHECK (projector_version > 0),
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  UNIQUE (source_raw_event_id, event_type, projector_version)
);

CREATE VIEW dividend_finalized_blocks_v1
WITH (security_barrier = true)
AS
SELECT
  environment_id,
  number AS block_number,
  hash AS block_hash,
  block_time
FROM chain_blocks
WHERE canonical AND finalized;

CREATE VIEW dividend_projection_coverage_v1
WITH (security_barrier = true)
AS
SELECT
  event.environment_id,
  event.deployment_set_id,
  stream.stream_key,
  event.id AS raw_event_id,
  event.block_number,
  event.block_hash,
  event.tx_index,
  event.log_index,
  receipt.projector_key,
  receipt.projector_version,
  receipt.status AS receipt_status
FROM chain_raw_events AS event
JOIN chain_streams AS stream ON stream.id = event.stream_id
LEFT JOIN projection_receipts AS receipt ON receipt.raw_event_id = event.id
WHERE event.canonical AND event.status = 'CONFIRMED';

CREATE VIEW dividend_token_balance_history_v1
WITH (security_barrier = true)
AS
SELECT
  event.environment_id,
  event.deployment_set_id,
  event.block_number,
  event.block_hash,
  event.tx_index,
  event.log_index,
  ledger.source_raw_event_id,
  ledger.account,
  ledger.counterparty,
  ledger.direction,
  ledger.amount_raw,
  ledger.reason,
  ledger.projector_version
FROM token_balance_ledger AS ledger
JOIN chain_raw_events AS event ON event.id = ledger.source_raw_event_id
JOIN chain_streams AS stream ON stream.id = event.stream_id
JOIN projection_receipts AS receipt
  ON receipt.raw_event_id = ledger.source_raw_event_id
  AND receipt.projector_key = 'token_ledger'
  AND receipt.projector_version = ledger.projector_version
  AND receipt.status = 'APPLIED'
WHERE event.canonical
  AND event.status = 'CONFIRMED'
  AND stream.stream_key = 'TOKEN';

CREATE VIEW dividend_staking_history_v1
WITH (security_barrier = true)
AS
SELECT
  event.environment_id,
  event.deployment_set_id,
  event.block_number,
  event.block_hash,
  event.tx_index,
  event.log_index,
  staking.source_raw_event_id,
  staking.account,
  staking.position_id,
  staking.event_type,
  staking.principal_raw,
  staking.reward_raw,
  staking.penalty_raw,
  staking.projector_version
FROM staking_events AS staking
JOIN chain_raw_events AS event ON event.id = staking.source_raw_event_id
JOIN chain_streams AS stream ON stream.id = event.stream_id
JOIN projection_receipts AS receipt
  ON receipt.raw_event_id = staking.source_raw_event_id
  AND receipt.projector_key = 'staking'
  AND receipt.projector_version = staking.projector_version
  AND receipt.status = 'APPLIED'
WHERE event.canonical
  AND event.status = 'CONFIRMED'
  AND stream.stream_key = 'STAKING';

CREATE TABLE dividend_epochs (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  epoch_id uint256_numeric NOT NULL,
  state text NOT NULL DEFAULT 'DRAFT' CHECK (state IN (
    'DRAFT','SNAPSHOT_BUILDING','SNAPSHOT_READY','APPROVAL_PENDING',
    'APPROVED','PUBLISH_QUEUED','CLAIM_OPEN','CLOSE_QUEUED','CLOSED',
    'CANCELLED','FAILED'
  )),
  snapshot_block_number bigint,
  snapshot_block_hash evm_hash,
  total_reward_raw uint256_numeric,
  merkle_root evm_hash,
  claim_start timestamptz,
  claim_end timestamptz,
  current_publish_command_id uuid,
  carry_raw uint256_numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  UNIQUE (environment_id, epoch_id),
  UNIQUE (id, environment_id, snapshot_block_number, snapshot_block_hash, total_reward_raw),
  CHECK ((snapshot_block_number IS NULL) = (snapshot_block_hash IS NULL)),
  CHECK (
    state IN ('DRAFT','CANCELLED','FAILED')
    OR snapshot_block_number IS NOT NULL
  ),
  CONSTRAINT dividend_epochs_snapshot_block_fk
    FOREIGN KEY (environment_id, snapshot_block_number, snapshot_block_hash)
    REFERENCES chain_blocks(environment_id, number, hash)
);

CREATE OR REPLACE FUNCTION enforce_dividend_snapshot_block()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF TG_OP = 'UPDATE' THEN
    IF OLD.snapshot_block_number IS NOT NULL
      AND ROW(NEW.environment_id, NEW.snapshot_block_number, NEW.snapshot_block_hash)
        IS DISTINCT FROM
        ROW(OLD.environment_id, OLD.snapshot_block_number, OLD.snapshot_block_hash)
    THEN
      RAISE EXCEPTION 'dividend snapshot block is immutable once selected'
        USING ERRCODE = '55000';
    END IF;
  END IF;

  IF NEW.snapshot_block_number IS NULL THEN
    RETURN NEW;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM chain_blocks AS block
    WHERE block.environment_id = NEW.environment_id
      AND block.number = NEW.snapshot_block_number
      AND block.hash = NEW.snapshot_block_hash
      AND block.canonical
      AND block.finalized
  ) THEN
    RAISE EXCEPTION 'dividend snapshot block must be canonical and finalized'
      USING ERRCODE = '23514';
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER dividend_epochs_snapshot_block_guard
BEFORE INSERT OR UPDATE OF environment_id, snapshot_block_number, snapshot_block_hash
ON dividend_epochs
FOR EACH ROW
EXECUTE FUNCTION enforce_dividend_snapshot_block();

CREATE OR REPLACE FUNCTION enforce_dividend_epoch_writer_boundary()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_user = 'bgp_migrator' THEN
    RETURN NEW;
  END IF;

  IF current_user = 'bgp_dividend' THEN
    IF NEW.merkle_root IS DISTINCT FROM OLD.merkle_root
      OR NEW.claim_start IS DISTINCT FROM OLD.claim_start
      OR NEW.claim_end IS DISTINCT FROM OLD.claim_end
      OR NEW.carry_raw IS DISTINCT FROM OLD.carry_raw
      OR (
        NEW.current_publish_command_id IS DISTINCT FROM OLD.current_publish_command_id
        AND NOT (
          OLD.state = 'FAILED'
          AND NEW.state = 'SNAPSHOT_BUILDING'
          AND NEW.current_publish_command_id IS NULL
        )
      )
    THEN
      RAISE EXCEPTION 'bgp_dividend cannot write projector-owned dividend epoch fields'
        USING ERRCODE = '55000';
    END IF;

    IF NEW.state = OLD.state THEN
      RETURN NEW;
    END IF;

    IF NOT (
      (OLD.state = 'DRAFT' AND NEW.state IN ('SNAPSHOT_BUILDING', 'CANCELLED'))
      OR (OLD.state = 'SNAPSHOT_BUILDING' AND NEW.state IN ('SNAPSHOT_READY', 'FAILED', 'CANCELLED'))
      OR (OLD.state = 'SNAPSHOT_READY' AND NEW.state IN ('APPROVAL_PENDING', 'SNAPSHOT_BUILDING', 'CANCELLED'))
      OR (OLD.state = 'APPROVAL_PENDING' AND NEW.state IN ('APPROVED', 'SNAPSHOT_BUILDING', 'CANCELLED'))
      OR (OLD.state = 'APPROVED' AND NEW.state IN ('PUBLISH_QUEUED', 'SNAPSHOT_BUILDING', 'CANCELLED'))
      OR (OLD.state = 'FAILED' AND NEW.state IN ('SNAPSHOT_BUILDING', 'CLOSE_QUEUED', 'CANCELLED'))
      OR (OLD.state = 'CLAIM_OPEN' AND NEW.state = 'CLOSE_QUEUED')
    ) THEN
      RAISE EXCEPTION 'bgp_dividend cannot apply dividend epoch transition % -> %', OLD.state, NEW.state
        USING ERRCODE = '55000';
    END IF;

    IF NEW.state = 'PUBLISH_QUEUED' AND NEW.current_publish_command_id IS NULL THEN
      RAISE EXCEPTION 'publish queue requires an immutable current publish command binding'
        USING ERRCODE = '55000';
    END IF;

    RETURN NEW;
  END IF;

  IF current_user = 'bgp_projector' THEN
    IF NEW.state = OLD.state THEN
      IF NEW.merkle_root IS DISTINCT FROM OLD.merkle_root
        OR NEW.claim_start IS DISTINCT FROM OLD.claim_start
        OR NEW.claim_end IS DISTINCT FROM OLD.claim_end
        OR NEW.current_publish_command_id IS DISTINCT FROM OLD.current_publish_command_id
      THEN
        RAISE EXCEPTION 'published dividend root and claim window are immutable'
          USING ERRCODE = '55000';
      END IF;
      RETURN NEW;
    END IF;

    IF NOT (
      (OLD.state = 'PUBLISH_QUEUED' AND NEW.state = 'CLAIM_OPEN')
      OR (OLD.state = 'CLOSE_QUEUED' AND NEW.state IN ('CLOSED', 'FAILED'))
    ) THEN
      RAISE EXCEPTION
        'bgp_projector cannot apply dividend epoch transition % -> %',
        OLD.state,
        NEW.state
        USING ERRCODE = '55000';
    END IF;

    IF NEW.state = 'CLAIM_OPEN' AND NEW.merkle_root IS NULL THEN
      RAISE EXCEPTION 'DividendRootPublished requires merkle_root on dividend_epochs'
        USING ERRCODE = '23514';
    END IF;

    IF OLD.state = 'PUBLISH_QUEUED' AND NEW.state = 'CLAIM_OPEN'
      AND OLD.merkle_root IS NOT NULL THEN
      RAISE EXCEPTION 'published dividend root is immutable and cannot be replaced'
        USING ERRCODE = '55000';
    END IF;

    IF NEW.state = 'CLAIM_OPEN'
      AND (NEW.claim_start IS NULL OR NEW.claim_end IS NULL) THEN
      RAISE EXCEPTION 'DividendRootPublished requires claim window on dividend_epochs'
        USING ERRCODE = '23514';
    END IF;

    RETURN NEW;
  END IF;

  -- A publish Command failure is an off-chain execution fact, not a projected
  -- contract event.  The Reconciler may record exactly this one failure edge,
  -- and only after the bound DIVIDEND_PUBLISH Command has reached a terminal
  -- non-success state in the same transaction.
  IF current_user = 'bgp_reconciler' THEN
    IF OLD.state <> 'PUBLISH_QUEUED' OR NEW.state <> 'FAILED' THEN
      RAISE EXCEPTION 'bgp_reconciler cannot apply dividend epoch transition % -> %', OLD.state, NEW.state
        USING ERRCODE = '55000';
    END IF;

    IF NEW.merkle_root IS DISTINCT FROM OLD.merkle_root
      OR NEW.claim_start IS DISTINCT FROM OLD.claim_start
      OR NEW.claim_end IS DISTINCT FROM OLD.claim_end
      OR NEW.carry_raw IS DISTINCT FROM OLD.carry_raw
      OR NEW.current_publish_command_id IS DISTINCT FROM OLD.current_publish_command_id THEN
      RAISE EXCEPTION 'bgp_reconciler cannot change dividend epoch evidence fields'
        USING ERRCODE = '55000';
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM governance_commands command
      JOIN dividend_publish_preflights preflight
        ON preflight.id = command.dividend_publish_preflight_id
      WHERE command.id = OLD.current_publish_command_id
        AND command.action = 'DIVIDEND_PUBLISH'
        AND preflight.dividend_epoch_id = OLD.id
        AND command.state IN ('FAILED', 'CANCELLED', 'EXPIRED')
    ) THEN
      RAISE EXCEPTION 'publish failure requires a terminal failed, cancelled, or expired bound command'
        USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'role % cannot update dividend_epochs', current_user
    USING ERRCODE = '42501';
END;
$$;

CREATE TRIGGER dividend_epochs_writer_boundary
BEFORE UPDATE OF
  state,
  merkle_root,
  claim_start,
  claim_end,
  current_publish_command_id,
  carry_raw,
  updated_at
ON dividend_epochs
FOR EACH ROW
EXECUTE FUNCTION enforce_dividend_epoch_writer_boundary();

CREATE TABLE dividend_artifacts (
  id uuid PRIMARY KEY,
  dividend_epoch_id uuid NOT NULL,
  environment_id uuid NOT NULL,
  snapshot_block_number bigint NOT NULL,
  snapshot_block_hash evm_hash NOT NULL,
  artifact_revision integer NOT NULL CHECK (artifact_revision > 0),
  supersedes_artifact_id uuid,
  algorithm_version text NOT NULL,
  schema_version text NOT NULL,
  projector_manifest jsonb NOT NULL CHECK (jsonb_typeof(projector_manifest) = 'object'),
  projector_manifest_sha256 varchar(64) NOT NULL CHECK (projector_manifest_sha256 ~ '^[0-9a-f]{64}$'),
  input_sha256 varchar(64) NOT NULL CHECK (input_sha256 ~ '^[0-9a-f]{64}$'),
  input_row_count bigint NOT NULL CHECK (input_row_count >= 0),
  content_sha256 varchar(64) NOT NULL CHECK (content_sha256 ~ '^[0-9a-f]{64}$'),
  merkle_root evm_hash NOT NULL,
  total_reward_raw uint256_numeric NOT NULL,
  object_uri text NOT NULL,
  row_count integer NOT NULL CHECK (row_count >= 0),
  created_at timestamptz NOT NULL,
  FOREIGN KEY (
    dividend_epoch_id,
    environment_id,
    snapshot_block_number,
    snapshot_block_hash,
    total_reward_raw
  ) REFERENCES dividend_epochs(
    id,
    environment_id,
    snapshot_block_number,
    snapshot_block_hash,
    total_reward_raw
  ),
  UNIQUE (dividend_epoch_id, artifact_revision),
  UNIQUE (id, dividend_epoch_id),
  FOREIGN KEY (supersedes_artifact_id, dividend_epoch_id)
    REFERENCES dividend_artifacts(id, dividend_epoch_id),
  UNIQUE (id, dividend_epoch_id, content_sha256, merkle_root, total_reward_raw),
  UNIQUE (
    id,
    dividend_epoch_id,
    environment_id,
    snapshot_block_number,
    snapshot_block_hash,
    content_sha256,
    merkle_root,
    total_reward_raw,
    input_sha256,
    projector_manifest_sha256
  ),
  UNIQUE (supersedes_artifact_id),
  CHECK (supersedes_artifact_id IS NULL OR supersedes_artifact_id <> id)
);

CREATE TABLE dividend_allocations (
  id uuid PRIMARY KEY,
  artifact_id uuid NOT NULL,
  dividend_epoch_id uuid NOT NULL,
  account evm_address NOT NULL,
  rank integer NOT NULL CHECK (rank BETWEEN 1 AND 100),
  tier integer NOT NULL CHECK (tier BETWEEN 1 AND 4),
  effective_balance_raw uint256_numeric NOT NULL,
  allocation_raw uint256_numeric NOT NULL,
  leaf_hash evm_hash NOT NULL,
  proof jsonb NOT NULL,
  FOREIGN KEY (artifact_id, dividend_epoch_id)
    REFERENCES dividend_artifacts(id, dividend_epoch_id),
  UNIQUE (artifact_id, account),
  UNIQUE (artifact_id, rank),
  UNIQUE (artifact_id, leaf_hash)
);

CREATE TABLE dividend_claims (
  id uuid PRIMARY KEY,
  dividend_epoch_id uuid NOT NULL REFERENCES dividend_epochs(id),
  account evm_address NOT NULL,
  amount_raw uint256_numeric NOT NULL,
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  claimed_at timestamptz NOT NULL,
  UNIQUE (dividend_epoch_id, account),
  UNIQUE (source_raw_event_id)
);

CREATE TABLE dividend_approvals (
  id uuid PRIMARY KEY,
  artifact_id uuid NOT NULL,
  dividend_epoch_id uuid NOT NULL,
  approval_type text NOT NULL CHECK (approval_type IN ('BUILD','PUBLISH','CLOSE','CANCEL')),
  admin_user_id uuid NOT NULL,
  decision text NOT NULL CHECK (decision IN ('APPROVE','REJECT')),
  artifact_sha256 varchar(64) NOT NULL CHECK (artifact_sha256 ~ '^[0-9a-f]{64}$'),
  expected_merkle_root evm_hash NOT NULL,
  expected_total_reward_raw uint256_numeric NOT NULL,
  decided_at timestamptz NOT NULL,
  FOREIGN KEY (
    artifact_id,
    dividend_epoch_id,
    artifact_sha256,
    expected_merkle_root,
    expected_total_reward_raw
  ) REFERENCES dividend_artifacts(
    id,
    dividend_epoch_id,
    content_sha256,
    merkle_root,
    total_reward_raw
  ),
  UNIQUE (artifact_id, approval_type, admin_user_id)
);

CREATE TABLE dividend_publish_preflights (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  artifact_id uuid NOT NULL,
  dividend_epoch_id uuid NOT NULL,
  validation_revision integer NOT NULL CHECK (validation_revision > 0),
  artifact_sha256 varchar(64) NOT NULL CHECK (artifact_sha256 ~ '^[0-9a-f]{64}$'),
  expected_merkle_root evm_hash NOT NULL,
  expected_total_reward_raw uint256_numeric NOT NULL,
  snapshot_block_number bigint NOT NULL,
  snapshot_block_hash evm_hash NOT NULL,
  projector_manifest_sha256 varchar(64) NOT NULL CHECK (projector_manifest_sha256 ~ '^[0-9a-f]{64}$'),
  input_sha256 varchar(64) NOT NULL CHECK (input_sha256 ~ '^[0-9a-f]{64}$'),
  coverage_sha256 varchar(64) NOT NULL CHECK (coverage_sha256 ~ '^[0-9a-f]{64}$'),
  coverage_event_count bigint NOT NULL CHECK (coverage_event_count >= 0),
  validator_version text NOT NULL,
  validated_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL,
  FOREIGN KEY (
    artifact_id,
    dividend_epoch_id,
    environment_id,
    snapshot_block_number,
    snapshot_block_hash,
    artifact_sha256,
    expected_merkle_root,
    expected_total_reward_raw,
    input_sha256,
    projector_manifest_sha256
  ) REFERENCES dividend_artifacts(
    id,
    dividend_epoch_id,
    environment_id,
    snapshot_block_number,
    snapshot_block_hash,
    content_sha256,
    merkle_root,
    total_reward_raw,
    input_sha256,
    projector_manifest_sha256
  ),
  FOREIGN KEY (environment_id, snapshot_block_number, snapshot_block_hash)
    REFERENCES chain_blocks(environment_id, number, hash),
  UNIQUE (artifact_id, validation_revision),
  UNIQUE (
    id,
    artifact_id,
    artifact_sha256,
    expected_merkle_root,
    expected_total_reward_raw
  ),
  CHECK (expires_at > validated_at)
);

CREATE OR REPLACE FUNCTION reject_dividend_evidence_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION '% rows are append-only', TG_TABLE_NAME
    USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER dividend_artifacts_append_only
BEFORE UPDATE OR DELETE ON dividend_artifacts
FOR EACH ROW EXECUTE FUNCTION reject_dividend_evidence_mutation();

CREATE TRIGGER dividend_allocations_append_only
BEFORE UPDATE OR DELETE ON dividend_allocations
FOR EACH ROW EXECUTE FUNCTION reject_dividend_evidence_mutation();

CREATE TRIGGER dividend_approvals_append_only
BEFORE UPDATE OR DELETE ON dividend_approvals
FOR EACH ROW EXECUTE FUNCTION reject_dividend_evidence_mutation();

CREATE TRIGGER dividend_publish_preflights_append_only
BEFORE UPDATE OR DELETE ON dividend_publish_preflights
FOR EACH ROW EXECUTE FUNCTION reject_dividend_evidence_mutation();

CREATE TABLE buybacks (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  caller evm_address NOT NULL,
  bnb_in_raw uint256_numeric NOT NULL,
  token_out_raw uint256_numeric NOT NULL,
  locker_batch_id uint256_numeric,
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  executed_at timestamptz NOT NULL,
  UNIQUE (source_raw_event_id)
);

CREATE TABLE locker_batches (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  batch_id uint256_numeric NOT NULL,
  amount_raw uint256_numeric NOT NULL,
  unlock_time timestamptz NOT NULL,
  recipient evm_address NOT NULL,
  state text NOT NULL CHECK (state IN ('LOCKED','RELEASED','PERMANENT')),
  lock_source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  release_source_raw_event_id uuid REFERENCES chain_raw_events(id),
  UNIQUE (environment_id, batch_id)
);

CREATE TABLE fee_vault_movements (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  movement_type text NOT NULL,
  token_amount_raw uint256_numeric NOT NULL DEFAULT 0,
  bnb_amount_raw uint256_numeric NOT NULL DEFAULT 0,
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  UNIQUE (source_raw_event_id, movement_type)
);

CREATE TABLE oracle_events (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  status text NOT NULL CHECK (status IN ('UNINITIALIZED','ACCUMULATING','READY','LIQUIDITY_LOW')),
  price_numerator_raw uint256_numeric,
  price_denominator_raw uint256_numeric,
  window_seconds integer,
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  UNIQUE (source_raw_event_id)
);

CREATE TABLE protocol_control_events (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  control_type text NOT NULL,
  subject evm_address,
  old_value jsonb,
  new_value jsonb,
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  UNIQUE (source_raw_event_id, control_type, subject)
);

CREATE TABLE role_events (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  contract_address evm_address NOT NULL,
  role_hash evm_hash NOT NULL,
  account evm_address NOT NULL,
  action text NOT NULL CHECK (action IN ('GRANT','REVOKE','RENOUNCE')),
  sender evm_address,
  source_raw_event_id uuid NOT NULL REFERENCES chain_raw_events(id),
  UNIQUE (source_raw_event_id, role_hash, account, action)
);

CREATE TABLE admin_users (
  id uuid PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role text NOT NULL CHECK (role IN ('SUPER_ADMIN','OPERATOR','AUDITOR','VIEWER')),
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE TABLE admin_sessions (
  id uuid PRIMARY KEY,
  admin_user_id uuid NOT NULL REFERENCES admin_users(id),
  token_hash varchar(64) NOT NULL UNIQUE,
  csrf_secret_hash varchar(64) NOT NULL,
  ip_hash varchar(64),
  user_agent_hash varchar(64),
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  CHECK (expires_at > created_at)
);

CREATE TABLE wallet_challenges (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  address evm_address NOT NULL,
  nonce_hash varchar(64) NOT NULL UNIQUE,
  message text NOT NULL,
  chain_id bigint NOT NULL CHECK (chain_id > 0 AND chain_id <> 56),
  issued_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  CHECK (expires_at > issued_at)
);

CREATE TABLE wallet_sessions (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  address evm_address NOT NULL,
  token_hash varchar(64) NOT NULL UNIQUE,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  CHECK (expires_at > created_at)
);

CREATE TABLE idempotency_records (
  id uuid PRIMARY KEY,
  scope text NOT NULL,
  idempotency_key text NOT NULL,
  request_hash varchar(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  resource_type text,
  resource_id uuid,
  response_code integer,
  response_body jsonb,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL,
  UNIQUE (scope, idempotency_key)
);

CREATE TABLE governance_commands (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  deployment_set_id uuid NOT NULL REFERENCES deployment_sets(id),
  action text NOT NULL,
  target_contract_key text NOT NULL,
  target_address evm_address NOT NULL,
  selector varchar(10) NOT NULL CHECK (selector ~ '^0x[0-9a-f]{8}$'),
  parameters jsonb NOT NULL,
  dividend_publish_preflight_id uuid REFERENCES dividend_publish_preflights(id),
  dividend_artifact_id uuid,
  dividend_artifact_sha256 varchar(64) CHECK (dividend_artifact_sha256 ~ '^[0-9a-f]{64}$'),
  dividend_expected_merkle_root evm_hash,
  dividend_expected_total_reward_raw uint256_numeric,
  request_hash varchar(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  requested_by uuid NOT NULL REFERENCES admin_users(id),
  state text NOT NULL CHECK (state IN (
    'CREATED','VALIDATED','PENDING_APPROVAL','APPROVED','QUEUED','SIGNING',
    'SUBMITTED','CONFIRMED','FINALIZED','REJECTED','CANCELLED','FAILED','EXPIRED'
  )),
  expires_at timestamptz,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL,
  FOREIGN KEY (
    dividend_publish_preflight_id,
    dividend_artifact_id,
    dividend_artifact_sha256,
    dividend_expected_merkle_root,
    dividend_expected_total_reward_raw
  ) REFERENCES dividend_publish_preflights(
    id,
    artifact_id,
    artifact_sha256,
    expected_merkle_root,
    expected_total_reward_raw
  ),
  CHECK (
    action <> 'DIVIDEND_PUBLISH'
    OR (
      dividend_publish_preflight_id IS NOT NULL
      AND dividend_artifact_id IS NOT NULL
      AND dividend_artifact_sha256 IS NOT NULL
      AND dividend_expected_merkle_root IS NOT NULL
      AND dividend_expected_total_reward_raw IS NOT NULL
    )
  )
);

ALTER TABLE dividend_epochs
  ADD CONSTRAINT dividend_epochs_current_publish_command_fk
  FOREIGN KEY (current_publish_command_id) REFERENCES governance_commands(id);

CREATE OR REPLACE FUNCTION bind_current_dividend_publish_command(
  p_epoch_id uuid,
  p_command_id uuid,
  p_updated_at timestamptz
)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = binggoplus_v2, pg_temp
AS $$
DECLARE
  epoch_state text;
  existing_command_id uuid;
BEGIN
  IF session_user <> 'bgp_api' THEN
    RAISE EXCEPTION 'only bgp_api may bind a current dividend publish command'
      USING ERRCODE = '42501';
  END IF;

  SELECT state, current_publish_command_id
    INTO epoch_state, existing_command_id
  FROM dividend_epochs
  WHERE id = p_epoch_id
  FOR UPDATE;

  IF NOT FOUND OR epoch_state <> 'APPROVED' OR existing_command_id IS NOT NULL THEN
    RAISE EXCEPTION 'publish command binding requires an approved epoch without a current attempt'
      USING ERRCODE = '55000';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM governance_commands command
    JOIN dividend_publish_preflights preflight
      ON preflight.id = command.dividend_publish_preflight_id
    WHERE command.id = p_command_id
      AND command.action = 'DIVIDEND_PUBLISH'
      AND command.state IN ('CREATED', 'VALIDATED', 'PENDING_APPROVAL', 'APPROVED')
      AND preflight.dividend_epoch_id = p_epoch_id
  ) THEN
    RAISE EXCEPTION 'current publish command must be an unsigned command bound to this epoch'
      USING ERRCODE = '55000';
  END IF;

  UPDATE dividend_epochs
  SET current_publish_command_id = p_command_id,
      updated_at = p_updated_at
  WHERE id = p_epoch_id;
END;
$$;

CREATE UNIQUE INDEX one_dividend_publish_command_per_preflight
  ON governance_commands(dividend_publish_preflight_id)
  WHERE action = 'DIVIDEND_PUBLISH'
    AND dividend_publish_preflight_id IS NOT NULL;

CREATE OR REPLACE FUNCTION reject_governance_command_binding_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF ROW(
    NEW.environment_id,
    NEW.deployment_set_id,
    NEW.action,
    NEW.target_contract_key,
    NEW.target_address,
    NEW.selector,
    NEW.parameters,
    NEW.request_hash,
    NEW.requested_by,
    NEW.expires_at,
    NEW.created_at,
    NEW.dividend_publish_preflight_id,
    NEW.dividend_artifact_id,
    NEW.dividend_artifact_sha256,
    NEW.dividend_expected_merkle_root,
    NEW.dividend_expected_total_reward_raw
  ) IS DISTINCT FROM ROW(
    OLD.environment_id,
    OLD.deployment_set_id,
    OLD.action,
    OLD.target_contract_key,
    OLD.target_address,
    OLD.selector,
    OLD.parameters,
    OLD.request_hash,
    OLD.requested_by,
    OLD.expires_at,
    OLD.created_at,
    OLD.dividend_publish_preflight_id,
    OLD.dividend_artifact_id,
    OLD.dividend_artifact_sha256,
    OLD.dividend_expected_merkle_root,
    OLD.dividend_expected_total_reward_raw
  ) THEN
    RAISE EXCEPTION 'governance command execution binding is immutable'
      USING ERRCODE = '55000';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER governance_commands_binding_guard
BEFORE UPDATE OF
  environment_id,
  deployment_set_id,
  action,
  target_contract_key,
  target_address,
  selector,
  parameters,
  request_hash,
  requested_by,
  expires_at,
  created_at,
  dividend_publish_preflight_id,
  dividend_artifact_id,
  dividend_artifact_sha256,
  dividend_expected_merkle_root,
  dividend_expected_total_reward_raw
ON governance_commands
FOR EACH ROW
EXECUTE FUNCTION reject_governance_command_binding_mutation();

CREATE TABLE governance_command_cancellation_requests (
  id uuid PRIMARY KEY,
  command_id uuid NOT NULL UNIQUE REFERENCES governance_commands(id),
  requested_by uuid NOT NULL REFERENCES admin_users(id),
  reason text NOT NULL CHECK (length(reason) BETWEEN 1 AND 2000),
  request_hash varchar(64) NOT NULL CHECK (request_hash ~ '^[0-9a-f]{64}$'),
  state text NOT NULL CHECK (state IN ('REQUESTED', 'CONSUMED', 'REJECTED')),
  created_at timestamptz NOT NULL,
  resolved_at timestamptz,
  CHECK ((state = 'REQUESTED' AND resolved_at IS NULL) OR (state IN ('CONSUMED', 'REJECTED') AND resolved_at IS NOT NULL))
);

CREATE OR REPLACE FUNCTION enforce_governance_command_state_transition()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF current_user = 'bgp_migrator' THEN
    RETURN NEW;
  END IF;

  IF NEW.state = OLD.state THEN
    RETURN NEW;
  END IF;

  IF current_user = 'bgp_api' THEN
    IF NOT (
      (OLD.state = 'CREATED' AND NEW.state IN ('VALIDATED', 'REJECTED', 'EXPIRED'))
      OR (OLD.state = 'VALIDATED' AND NEW.state IN ('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'EXPIRED'))
      OR (OLD.state = 'PENDING_APPROVAL' AND NEW.state IN ('APPROVED', 'REJECTED', 'EXPIRED'))
    ) THEN
      RAISE EXCEPTION 'bgp_api cannot apply governance command transition % -> %', OLD.state, NEW.state
        USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
  END IF;

  IF current_user = 'bgp_reconciler' THEN
    IF NOT (
      (OLD.state = 'CREATED' AND NEW.state = 'CANCELLED')
      OR (OLD.state = 'VALIDATED' AND NEW.state = 'CANCELLED')
      OR (OLD.state = 'PENDING_APPROVAL' AND NEW.state = 'CANCELLED')
      OR (OLD.state = 'APPROVED' AND NEW.state IN ('QUEUED', 'CANCELLED', 'EXPIRED'))
      OR (OLD.state = 'QUEUED' AND NEW.state IN ('SIGNING', 'CANCELLED', 'FAILED', 'EXPIRED'))
      OR (OLD.state = 'SIGNING' AND NEW.state IN ('SUBMITTED', 'FAILED'))
      OR (OLD.state = 'SUBMITTED' AND NEW.state IN ('CONFIRMED', 'FAILED'))
      OR (OLD.state = 'CONFIRMED' AND NEW.state IN ('FINALIZED', 'FAILED'))
    ) THEN
      RAISE EXCEPTION 'bgp_reconciler cannot apply governance command transition % -> %', OLD.state, NEW.state
        USING ERRCODE = '55000';
    END IF;
    IF NEW.state = 'CANCELLED' AND NOT EXISTS (
      SELECT 1 FROM governance_command_cancellation_requests request
      WHERE request.command_id = OLD.id AND request.state = 'REQUESTED'
    ) THEN
      RAISE EXCEPTION 'reconciler cancellation requires a pending immutable cancellation request'
        USING ERRCODE = '55000';
    END IF;
    IF OLD.state = 'QUEUED' AND NEW.state = 'SIGNING' AND EXISTS (
      SELECT 1 FROM governance_command_cancellation_requests request
      WHERE request.command_id = OLD.id AND request.state = 'REQUESTED'
    ) THEN
      RAISE EXCEPTION 'queued command with a pending cancellation request cannot enter signing'
        USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'role % cannot update governance command state', current_user
    USING ERRCODE = '42501';
END;
$$;

CREATE TRIGGER governance_commands_state_transition_guard
BEFORE UPDATE OF state ON governance_commands
FOR EACH ROW
EXECUTE FUNCTION enforce_governance_command_state_transition();

CREATE OR REPLACE FUNCTION enforce_governance_command_cancellation_request_boundary()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  command_state text;
BEGIN
  IF current_user = 'bgp_migrator' THEN
    RETURN COALESCE(NEW, OLD);
  END IF;

  IF TG_OP = 'INSERT' THEN
    IF current_user <> 'bgp_api' OR NEW.state <> 'REQUESTED' OR NEW.resolved_at IS NOT NULL THEN
      RAISE EXCEPTION 'only bgp_api may create a pending cancellation request'
        USING ERRCODE = '42501';
    END IF;
    SELECT state INTO command_state FROM governance_commands WHERE id = NEW.command_id FOR SHARE;
    IF command_state NOT IN ('CREATED', 'VALIDATED', 'PENDING_APPROVAL', 'APPROVED', 'QUEUED') THEN
      RAISE EXCEPTION 'cancellation request requires an unsigned cancellable command'
        USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
  END IF;

  IF TG_OP = 'UPDATE' THEN
    IF current_user <> 'bgp_reconciler'
      OR ROW(NEW.command_id, NEW.requested_by, NEW.reason, NEW.request_hash, NEW.created_at)
         IS DISTINCT FROM ROW(OLD.command_id, OLD.requested_by, OLD.reason, OLD.request_hash, OLD.created_at)
      OR OLD.state <> 'REQUESTED'
      OR NEW.state NOT IN ('CONSUMED', 'REJECTED')
      OR NEW.resolved_at IS NULL THEN
      RAISE EXCEPTION 'cancellation intent is immutable and only bgp_reconciler may resolve it'
        USING ERRCODE = '55000';
    END IF;

    SELECT state INTO command_state
    FROM governance_commands
    WHERE id = NEW.command_id
    FOR SHARE;

    IF NEW.state = 'CONSUMED' AND command_state <> 'CANCELLED' THEN
      RAISE EXCEPTION 'cancellation request may be consumed only with a cancelled command'
        USING ERRCODE = '55000';
    END IF;

    IF NEW.state = 'REJECTED' AND command_state NOT IN (
      'SIGNING', 'SUBMITTED', 'CONFIRMED', 'FINALIZED', 'FAILED', 'EXPIRED', 'REJECTED'
    ) THEN
      RAISE EXCEPTION 'pending cancellation cannot be rejected while command remains cancellable'
        USING ERRCODE = '55000';
    END IF;
    RETURN NEW;
  END IF;

  RAISE EXCEPTION 'cancellation requests are append-only' USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER governance_command_cancellation_requests_boundary
BEFORE INSERT OR UPDATE OR DELETE ON governance_command_cancellation_requests
FOR EACH ROW
EXECUTE FUNCTION enforce_governance_command_cancellation_request_boundary();

CREATE TABLE governance_approvals (
  id uuid PRIMARY KEY,
  command_id uuid NOT NULL REFERENCES governance_commands(id),
  admin_user_id uuid NOT NULL REFERENCES admin_users(id),
  decision text NOT NULL CHECK (decision IN ('APPROVE','REJECT')),
  reason text,
  decided_at timestamptz NOT NULL,
  UNIQUE (command_id, admin_user_id)
);

CREATE TABLE signer_nonces (
  environment_id uuid NOT NULL REFERENCES environments(id),
  signer_address evm_address NOT NULL,
  next_nonce bigint NOT NULL CHECK (next_nonce >= 0),
  lease_owner text,
  lease_expires_at timestamptz,
  fencing_token bigint NOT NULL CHECK (fencing_token > 0),
  updated_at timestamptz NOT NULL,
  PRIMARY KEY (environment_id, signer_address)
);

CREATE TABLE governance_tx_attempts (
  id uuid PRIMARY KEY,
  command_id uuid NOT NULL REFERENCES governance_commands(id),
  environment_id uuid NOT NULL REFERENCES environments(id),
  attempt_no integer NOT NULL CHECK (attempt_no > 0),
  signer_address evm_address NOT NULL,
  nonce bigint NOT NULL CHECK (nonce >= 0),
  tx_hash evm_hash,
  raw_tx_hash evm_hash,
  replaces_attempt_id uuid REFERENCES governance_tx_attempts(id),
  state text NOT NULL CHECK (state IN ('SIGNED','BROADCAST','MINED_SUCCESS','MINED_REVERT','REPLACED','DROPPED','FAILED')),
  receipt jsonb,
  submitted_at timestamptz,
  mined_at timestamptz,
  created_at timestamptz NOT NULL,
  UNIQUE (command_id, attempt_no)
);
CREATE UNIQUE INDEX one_live_attempt_per_signer_nonce
  ON governance_tx_attempts(environment_id, signer_address, nonce)
  WHERE state IN ('SIGNED','BROADCAST','MINED_SUCCESS','MINED_REVERT');

CREATE TABLE admin_audit_logs (
  id uuid PRIMARY KEY,
  admin_user_id uuid REFERENCES admin_users(id),
  request_id uuid NOT NULL,
  action text NOT NULL,
  resource_type text,
  resource_id text,
  outcome text NOT NULL CHECK (outcome IN ('ALLOWED','DENIED','SUCCESS','FAILURE')),
  before_value jsonb,
  after_value jsonb,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL
);
CREATE INDEX audit_log_time ON admin_audit_logs(created_at DESC);

CREATE OR REPLACE FUNCTION reject_admin_audit_log_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'admin_audit_logs is append-only: UPDATE and DELETE are forbidden'
    USING ERRCODE = '55000';
END;
$$;

CREATE TRIGGER admin_audit_logs_append_only
BEFORE UPDATE OR DELETE ON admin_audit_logs
FOR EACH ROW
EXECUTE FUNCTION reject_admin_audit_log_mutation();

CREATE TABLE job_runs (
  id uuid PRIMARY KEY,
  environment_id uuid REFERENCES environments(id),
  job_type text NOT NULL,
  dedupe_key text,
  state text NOT NULL CHECK (state IN ('QUEUED','RUNNING','SUCCEEDED','FAILED','CANCELLED','DEAD_LETTER')),
  input jsonb NOT NULL DEFAULT '{}'::jsonb,
  output jsonb,
  error jsonb,
  attempt integer NOT NULL DEFAULT 0 CHECK (attempt >= 0),
  started_at timestamptz,
  finished_at timestamptz,
  created_at timestamptz NOT NULL
);
CREATE UNIQUE INDEX job_dedupe_active
  ON job_runs(job_type, dedupe_key)
  WHERE dedupe_key IS NOT NULL AND state IN ('QUEUED','RUNNING');

CREATE TABLE system_anomalies (
  id uuid PRIMARY KEY,
  environment_id uuid NOT NULL REFERENCES environments(id),
  anomaly_key text NOT NULL,
  severity text NOT NULL CHECK (severity IN ('P0','P1','P2','P3','INFO')),
  status text NOT NULL CHECK (status IN ('OPEN','ACKNOWLEDGED','MITIGATING','RESOLVED','RISK_ACCEPTED')),
  observed_block_number bigint,
  observed_block_hash evm_hash,
  evidence jsonb NOT NULL,
  opened_at timestamptz NOT NULL,
  resolved_at timestamptz
);

ALTER TABLE dividend_approvals
  ADD CONSTRAINT dividend_approvals_admin_user_fk
  FOREIGN KEY (admin_user_id) REFERENCES admin_users(id);

COMMIT;
