[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
via_ir = true
bytecode_hash = "ipfs"
cbor_metadata = true
fuzz = { runs = 10000 }
invariant = { runs = 512, depth = 64, fail_on_revert = true }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
